project:
  type: website

website:
  title: "akashBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/akashprakas
      - icon: twitter
        href: https://twitter.com/akashaapz
format:
  html:
    toc: true
    toc-location: right
    grid:
      body-width: 1200px      # <- widen the main content column
      margin-width: 200px     # <- width of the right margin (TOC column)
      gutter-width: 1.5rem    # <- spacing between columns



